StartupEvents.registry("block", (event) => {
    event.create("computer")
    .model("kubejs/assets/models/computer.json")
    .renderType("solid")
    .displayName("Computer")
    .mapColor("metal")
    .soundType("metal")
    .hardness(5.0)
    .resistance(100.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock("minecraft:needs_iron_tool")
    .lightLevel(4)
    .box(x0, y0, z0, x16, y16, z16, true)
})

StartupEvents.registry("block", (event) => {
    event.create("monitor")
    .renderType("solid")
    .displayName("Monitor")
    .mapColor("metal")
    .soundType("metal")
    .hardness(5.0)
    .resistance(100.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock("minecraft:needs_iron_tool")
    .lightLevel(4)
    .texture('north', 'kubejs:block/monitor_f.png')
    .texture('south', 'kubejs:block/computer_sides.png')
    .texture('east', 'kubejs:block/computer_sides.png')
    .texture('west', 'kubejs:block/computer_sides.png')
    .texture('up', 'kubejs:block/computer_sides.png')
    .texture('down', 'kubejs:block/computer_sides.png')
    .box(x0, y0, z0, x16, y16, z16, true)
})
