StartupEvents.registry("block", (event) => {
    event.create("computer")
    .model("kubejs/assets/models/computer.json")
    .renderType("solid")
    .displayName("Computer")
    .mapColor("metal")
    .soundType("metal")
    .hardness(5.0)
    .resistance(100.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock("minecraft:needs_iron_tool")
    .lightLevel(4)
    .textureAll("kubejs/assets/textures/computer_sides.png")
})

StartupEvents.registry("block", (event) => {
    event.create("monitor")
    .renderType("solid")
    .displayName("Monitor")
    .mapColor("metal")
    .soundType("metal")
    .hardness(5.0)
    .resistance(100.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock("minecraft:needs_iron_tool")
    .lightLevel(4)
    .texture('north', 'kubejs/assets/kubejs/textures/block/monitor_f.png')
    .texture('south', 'kubejs/assets/kubejs/textures/block/computer_sides.png')
    .texture('east', 'kubejs/assets/kubejs/textures/block/computer_sides.pngg')
    .texture('west', 'kubejs/assets/kubejs/textures/block/computer_sides.png')
    .texture('up', 'kubejs/assets/kubejs/textures/block/computer_sides.png')
    .texture('down', 'kubejs/assets/kubejs/textures/block/computer_sides.png')
})
